version: "3"

services:
  juice-shop:
    image: bkimminich/juice-shop:v14.3.1
    ports:
      - ${JUICE_SHOP_PORT}:3000

  mongo-db:
    image: mongo:5.0
    ports:
      - ${MONGO_DB_PORT}:27017

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
